### ISSUE TITLE
Create a unit test for the generation of table M

### ISSUE THREAD

**Issue by chatox** [fair-search/fairsearch-elasticsearch-plugin#18]
The generation of table M should be covered by unit tests varying p, alpha, and k.

Typical values of alpha: 0.1, 0.2

Values of k: 50, 100, 200

Values of p: 0.4, 0.5, 0.6

**Comment by purbon** [comment]
related to #1

**Comment by purbon** [comment]
@tsuehr can you take a look here and update the unit testing?

**Comment by tsuehr** [comment]
i opened a pr but its not finished yet

**Comment by purbon** [comment]
More test where added with #21 also more are coming with #26

**Comment by tsuehr** [comment]
i will wait with colsing this issue until i worked everything out for the alpha adjustment research in general. For our first release however, all cases are added

**Comment by tsuehr** [comment]
done
